### ISSUE TITLE
fbdev: Triple-buffering

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL-1.2#817]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [Patch to fix the issue (file_4948.txt, text/plain, 2020-01-13 18:20:39 +0000, 9532 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=4164)

**Reported in version:** HG 1.2
**Reported for operating system, platform:** Linux, All

# Comments on the original bug report:

On 2020-01-13 18:20:39 +0000, Paul Cercueil wrote:

> Created attachment 4164
> Patch to fix the issue
> 
> From the patch:
> 
> "Implement triple-buffering using a dedicated thread which will wait on
> VSYNC and then flip the two back buffers."

On 2020-09-22 02:11:12 +0000, Ozkan Sezer wrote:

> The patch is in. Thanks.
> http://hg.libsdl.org/SDL/rev/3dfb9493a246

**Comment by sezero** [comment]
@pcercuei: Newly added `SDL_TRIPLEBUF`, 0x40000100, actually equals to
`SDL_DOUBLEBUF | SDL_HWACCEL`: Was this your intention? Haven't look at
things too closely yet, but can that not lead to confusions?

**Comment by pcercuei** [comment]
Looks like a bug. The intention was to use a value that would have the `SDL_DOUBLEBUF` bit set, so that an app compiled with `SDL_TRIPLEBUF` would still run on an older version of SDL but with double-buffering.

I *think* it shouldn't have any side effect, though. The `SDL_HWACCEL` flag is used for tagging source surfaces of blits, and the main video surface will never be the source of a blit. On the other hand, the `SDL_TRIPLEBUF` will only ever be used on the main video surface. So the 0x100 bit has two purposes that should never overlap.

If you prefer to change the `SDL_TRIPLEBUF` macro, the video init function could have a workaround for converting `SDL_DOUBLEBUF | SDL_HWACCEL` to the new `SDL_TRIPLEBUF`, since you're never supposed to pass SDL_HWACCEL to SDL_SetVideoMode. We have a lot of software compiled with `SDL_TRIPLEBUF` now, and they all would break if we changed the macro value without a workaround.

**Comment by sezero** [comment]
> Looks like a bug. The intention was to use a value that would have the `SDL_DOUBLEBUF` bit set, so that an app compiled with `SDL_TRIPLEBUF` would still run on an older version of SDL but with double-buffering.

Looking at other flags, I guess 0x40100000 only would be safe in every case

>  We have a lot of software compiled with `SDL_TRIPLEBUF` now, and they all would break if we changed the macro value without a workaround.

Recompiling is not an option?

**Comment by pcercuei** [comment]
Not an option, we're talking about 200+ apps compiled by the same number of people over ~8 years.

If you don't want the workaround, I can have it as a local patch in our distribution.

**Comment by slouken** [comment]
@pcercuei: What is your use case for this? We're recommending that new development use SDL 2.0, but what are you working on that has over 200+ apps on the framebuffer console?

**Comment by pcercuei** [comment]
@slouken OpenDingux linux distribution, for the GCW-Zero, Anbernic RG-350, and a bunch of other chinese handheld gaming consoles.

I'd use SDL 2.0 if it worked for us.

But SDL 2.0 dropped the fbdev backend, the KMS/DRM backend barely works, no clear separation between renderers and video output (e.g. the KMS/DRM backend *requires* GL), and just performs terrible for the apps that render in software and only want to display their buffer (e.g. emulators) because of the rendering path, where the buffer is uploaded as a texture to the GPU, which will then render it to a video buffer, while in SDL1 the apps can render directly into the video buffer.

**Comment by slouken** [comment]
That makes sense. I'll add a task to re-add fbdev support for SDL 2.0. We dropped it mainly because we weren't aware of any significant use of that backend.

Ozkan, let's leave SDL 1.2 as-is and not fix this discrepancy.

Thanks!

**Comment by sezero** [comment]
>  leave SDL 1.2 as-is and not fix this discrepancy.

@slouken: Keep the patch in as it is, yes? (not a native speaker, sorry.)

**Comment by pcercuei** [comment]
@slouken  Note that we don't use the fbdev backend of SDL1 anymore, we switched to a KMS/DRM backend that I can contribute back once it's cleaned up a bit. It works on atomic KMS drivers and does not require OpenGL, EGL or even GBM/Mesa. Check it out: https://github.com/OpenDingux/SDL/tree/fix-integer-scaled/src/video/kmsdrm

We'd use the KMS/DRM backend of SDL 2.0, but it needs to be decoupled from GBM and OpenGL, much like our SDL1 implementation, and needs to offer the possibility for the apps to render directly into a KMS dumb buffer. That would be more useful for us than a fbdev backend.

**Comment by slouken** [comment]
> > leave SDL 1.2 as-is and not fix this discrepancy.
> 
> @slouken: Keep the patch in as it is, yes? (not a native speaker, sorry.)

Yes, that's correct.

**Comment by slouken** [comment]
> @slouken Note that we don't use the fbdev backend of SDL1 anymore, we switched to a KMS/DRM backend that I can contribute back once it's cleaned up a bit. It works on atomic KMS drivers and does not require OpenGL, EGL or even GBM/Mesa. Check it out: https://github.com/OpenDingux/SDL/tree/fix-integer-scaled/src/video/kmsdrm
> 
> We'd use the KMS/DRM backend of SDL 2.0, but it needs to be decoupled from GBM and OpenGL, much like our SDL1 implementation, and needs to offer the possibility for the apps to render directly into a KMS dumb buffer. That would be more useful for us than a fbdev backend.

Would you be willing to contribute an update for the SDL 2.0 backend that has that decoupling? I'm happy to work with you on the design, if that's helpful.

We don't need the SDL 1.2 patch, we're not planning any further SDL 1.2 releases.

**Comment by sezero** [comment]
> Yes, that's correct.

OK, closing.

**Comment by pcercuei** [comment]
> Would you be willing to contribute an update for the SDL 2.0 backend that has that decoupling? I'm happy to work with you on the design, if that's helpful.

Yes, that's somewhere on my TODO list, but I don't know when I'll have time to start working on this.

**Comment by slouken** [comment]
> > Would you be willing to contribute an update for the SDL 2.0 backend that has that decoupling? I'm happy to work with you on the design, if that's helpful.
> 
> Yes, that's somewhere on my TODO list, but I don't know when I'll have time to start working on this.

Fair enough. :)
