### ISSUE TITLE
The key you just pressed is not recognized by SDL (XF86BrightnessAuto)

### ISSUE THREAD

**Issue by jpretori** [libsdl-org/SDL-1.2#875]
I was playing Factorio - I had started it from the commandline.  When I quit the game, I found this in the terminal.  I'm not sure what key I pressed to achieve this result.  I was using my laptop keyboard at the time.

The key you just pressed is not recognized by SDL. To help get this fixed, please report this to the SDL forums/mailing list <https://discourse.libsdl.org/> X11 KeyCode 252 (244), X11 KeySym 0x100810F4 (XF86BrightnessAuto).

**Comment by icculus** [comment]
So we took this message out of SDL3 (and later SDL2 releases) because it just generates bugs we can't really do anything with and annoys users.

This message was never in SDL 1.2--[it landed in SDL 1.3](https://github.com/libsdl-org/SDL-historical-archive/commit/b582738dbefea54451acae8f087b2d3e54fb31af)--so I'm assuming this is sdl12-compat backed by an older SDL2 release. In any case, I'm closing this one as WONTFIX.
